### ISSUE TITLE
[HELP APPRECIATED] Cannot install msbuild

### ISSUE THREAD

**Issue by ben-biddington** [anthonychu/aspnet-4.x-docker-windows-container#5]
Hi there,

I have tried installing this demo but for some reason msbuild is not being installed at all.

Docker build succeeds otherwise

Any ideas?

(Tried [downloading BuildTools_Full.exe](https://raw.githubusercontent.com/alexellis/aspnet-voteservice/master/images/msbuild/Dockerfile), too, but that doesn't work either)

**Comment by ben-biddington** [comment]
I am getting the same error has [here](https://github.com/Microsoft/dotnet-framework-docker/issues/23), so must be version thing

**Comment by mbadawi23** [comment]
I was able to get around this using the following line:

`RUN & "C:\temp\bin\BuildTools_Full.exe /Silent /Full | out-null";`

Now this test returns `true` (I'm installing MSBuild 12):

`RUN & "Test-Path 'C:\Program Files (x86)\MSBuild\12.0\bin'";`
